
(spacemacs/declare-prefix (kbd "av") "voice")
(spacemacs/set-leader-keys (kbd "avv") 'serenade-mode)
(spacemacs/set-leader-keys (kbd "avl") 'serenade--log-open-log)
(spacemacs/set-leader-keys (kbd "avc") 'serenade-helm-commands)
(spacemacs/set-leader-keys (kbd "avj") 'serenade-open-autogenerated-file)
(spacemacs/set-leader-keys (kbd "avc") 'serenade--log-clear-log)
